// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionHistoryItem } from "./PositionHistoryItem";

export interface BestPos { pos: PositionHistoryItem | null, deep_eval: number, }