// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceCount } from "./PieceCount";

export interface PosState { black: PieceCount, white: PieceCount, }