// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export interface Figure { pos: number, color: Color, is_king: boolean, stricken: boolean, }