// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vector } from "./Vector";

export interface PositionEnvironment { size: number, vectors_map: Array<Array<Vector<number>>>, board_to_pack: Array<number>, pack_to_board: Array<number>, }