// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";
import type { StraightStrike } from "./StraightStrike";

export interface Strike { vec: Array<StraightStrike>, took_pieces: Array<Piece | null>, king_move: boolean, }